
name: Incloud_Github_Fuzzing

on:
    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev
        
      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go
          
      - name: Running ParamSpider
        shell: bash
        run: |
          pip3 install -r ParamSpider/requirements.txt
          chmod +x run.py
          python3 run.py

      - name: 安装依赖项
        run: sudo apt-get install libpcap-dev

      - name: 安装 ProjectDiscovery 工具
        env:
          GO111MODULE: on
        run: |
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest
          go install github.com/ffuf/ffuf@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Running SubFinder for passive DNS enumeration
        run: |
          subfinder -dL input/domains.txt -config config/subfinder-config.yaml -o output/passive_subdomains.txt
        shell: bash

      - name: Running dnsx for valid DNS filtering 
        run: |
          dnsx -l output/passive_subdomains.txt -t 50 | tee output/active_subdomains.txt
        shell: bash

      - name: Running naabu to check top 1000 ports
        run: |
          naabu -l output/active_subdomains.txt  -rate 10000 -top-ports 1000 | tee output/active_ports.txt
        shell: bash


      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -title
          httpx -l output/active_ports.txt | tee output/active_urls.txt
        shell: bash
        
      - name: Running dirscan 
        run: |
          wget https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
          mkdir dirout
          set +e ;time for i in $(cat output/active_urls.txt );do ffuf -w dicc.txt -u $i/FUZZ -t 200 -mc 200 -ac -recursion -v -of csv -o dirout/`date +%Y%m%d%H%M%S`.csv; done
          cat dirout/*.csv >> output/dirout.csv
        shell: bash

      
      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
            urls: output/dirout.csv
            templates: nuclei-templates/
            output: output/vuln.txt

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/vuln.txt
          
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/vuln.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "2991885177@qq.com"
          git config --global user.name "joejoequte"
          git commit -m "Nuclei Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
