
name: Incloud_Github_Fuzzing

on:
    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev
        
      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go
          
      - name: Running ParamSpider
        shell: bash
        run: |
          pip3 install -r ParamSpider/requirements.txt
          chmod +x run.py
          python3 run.py

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
            urls: output.txt
            templates: nuclei-templates/
            output: vuln.txt

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add vuln.txt
          
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add vuln.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "2991885177@qq.com"
          git config --global user.name "joejoequte"
          git commit -m "Nuclei Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: ${{ github.ref }}
